### ISSUE TITLE
Please change the gun ,add gun ,fix the no knockback

### ISSUE THREAD

**Issue by SpacyBenGnu** [InfinityGamers/Weapons#16]
Why therrs no knockback when u shoot the enemy?? And change the gun example for panzerfaust 419 = diamond horse armor because i want to put resourcepack for the gun ,

**Comment by KadTheHunter** [comment]
Please note that I'm not the dev and thus can't help fix any issues in the code, but I'm still responding here since the dev hasn't responded to anyone at all.

Knockback and Gun IDs can be changed in the [config.yml](https://github.com/InfinityGamers/Weapons/blob/master/resources/config.yml), in order to use that please use [Dev Build #4](https://poggit.pmmp.io/ci/InfinityGamers/Weapons/Weapons/dev:4) and edit the values accordingly.
For the guns just change the Gun IDs to whatever the IDs of guns are in your resourcepack, and the same for ammunition.
Knockback can be edited in the settings for each gun.

**Comment by xBeastMode** [comment]
This is an experimental plugin, it is not meant to be used in production servers. Most of my open source work is experiemental and I don't plan on updating it any longer.
